@base_url = http://localhost:8000

### Obtain JWT token
# @name login
POST {{base_url}}/auth/token/
content-type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
@jwt = {{login.response.body.access}}

### Get users
GET {{base_url}}/auth/users
Authorization: Bearer {{jwt}}
