# Generated by Django 5.1.1 on 2024-12-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionsset",
            name="permissions",
            field=models.ManyToManyField(blank=True, to="auth.permission"),
        ),
    ]
