# Generated by Django 5.1 on 2024-08-10 20:59

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupdetails',
            options={'verbose_name': 'Detalle de grupo', 'verbose_name_plural': 'Detalles de grupos'},
        ),
        migrations.AlterModelManagers(
            name='groupdetails',
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='groupdetails',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='groupdetails',
            name='group_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group'),
            preserve_default=False,
        ),
    ]
