# Generated by Django 5.1 on 2024-08-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_permissionsset_content_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionsset',
            options={'verbose_name': 'Conjunto de permisos', 'verbose_name_plural': 'Conjuntos de permisos'},
        ),
        migrations.AlterField(
            model_name='groupdetails',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
