# Generated by Django 5.1 on 2024-08-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_permissionsset_order_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionsset',
            name='label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
