# Generated by Django 5.1 on 2024-08-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_alter_groupdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupdetails',
            options={'verbose_name': 'Grupo de autorización', 'verbose_name_plural': 'Grupos de autorización'},
        ),
        migrations.CreateModel(
            name='PermissionsSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, related_name='permissions_set', to='users.groupdetails')),
                ('permissions', models.ManyToManyField(to='auth.permission')),
            ],
        ),
    ]
