# Generated by Django 5.1 on 2024-08-12 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_permissionsset_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionsset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.permissionsset'),
        ),
    ]
