# Generated by Django 5.1 on 2024-08-12 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0004_permissionsset_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionsset',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='permissionsset',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
