# Generated by Django 5.0.6 on 2024-06-24 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('municipality_dane_code', models.CharField(max_length=10)),
                ('departament_dane_code', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=100)),
                ('departament', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'city',
            },
        ),
        migrations.CreateModel(
            name='Diagnoses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=300)),
                ('extra', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'diagnoses',
                'verbose_name_plural': 'diagnoses',
            },
        ),
        migrations.CreateModel(
            name='GeneralExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specialities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name': 'speciality',
                'verbose_name_plural': 'speciality',
            },
        ),
        migrations.CreateModel(
            name='SystemsReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Thirds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('second_last_name', models.CharField(max_length=100)),
                ('date_birth', models.DateField()),
                ('year_old', models.IntegerField()),
                ('sex', models.CharField(choices=[('P', 'Paciente'), ('M', 'Medico')], max_length=1)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('P', 'Paciente'), ('M', 'Medico')], max_length=1)),
                ('city', models.CharField(max_length=100)),
                ('city_birth', models.CharField(max_length=100)),
                ('maternity_pregnancy', models.CharField(choices=[('NI', 'Ninguno'), ('PT', 'Primer Trimestre'), ('ST', 'Segundo Trimestre'), ('TT', 'Tercer Trimestre'), ('PU', 'Puérperio')], max_length=2)),
                ('maternity_breasfeeding', models.CharField(choices=[('0', 'Ninguno'), ('1', 'Menos de 1 mes'), ('2', '1 a 3 meses'), ('3', '3 a 6 meses'), ('4', 'Mas de 6 meses'), ('5', 'Mas de 1 año')], max_length=1)),
                ('maternity_breasfeeding_extend', models.CharField(choices=[('0', 'Nunca'), ('1', 'Menos de 1 Mes'), ('2', '1 a 3 meses'), ('3', '3 a 6 meses')], max_length=1)),
                ('maternity_breasfeeding_complementary', models.CharField(choices=[('0', 'Nunca'), ('1', 'Menos de 1 Mes'), ('2', '1 a 3 meses'), ('3', '3 a 6 meses')], max_length=1)),
                ('maternity_violence', models.CharField(choices=[('N', 'Ninguno'), ('M', 'Mina ANtipersona'), ('D', 'Desmovilizado'), ('R', 'Reinsertado'), ('I', 'Intrafamiliar')], max_length=1)),
                ('ethnicity', models.CharField(choices=[('N', 'Ninguno'), ('I', 'Indigena'), ('A', 'AfroColombiano'), ('G', 'ROM - Gitano'), ('R', 'Raizal')], max_length=1)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicalrecords.specialities')),
            ],
            options={
                'verbose_name': 'thirds',
                'verbose_name_plural': 'thirds',
                'db_table': 'thirds',
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason_consultation', models.CharField(max_length=100)),
                ('history', models.CharField(max_length=100)),
                ('systems_review', models.CharField(max_length=100)),
                ('general_exam', models.CharField(max_length=100)),
                ('allergies', models.BooleanField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(blank=True, limit_choices_to={'diagnoses__name': 'Diagnostico'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='medicalrecords.diagnoses', verbose_name='Diagnostico')),
                ('diagnosis_1', models.ForeignKey(blank=True, limit_choices_to={'diagnoses__name': 'Diagnostico'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_1', to='medicalrecords.diagnoses', verbose_name='Primer Diagnostico')),
                ('diagnosis_2', models.ForeignKey(blank=True, limit_choices_to={'diagnoses__name': 'Diagnostico'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_2', to='medicalrecords.diagnoses', verbose_name='Segundo Diagnostico')),
                ('diagnosis_3', models.ForeignKey(blank=True, limit_choices_to={'diagnoses__name': 'Diagnostico'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_3', to='medicalrecords.diagnoses', verbose_name='Tercer Diagnostico')),
                ('types_general_exam', models.ManyToManyField(to='medicalrecords.generalexam')),
                ('types_systems_review', models.ManyToManyField(to='medicalrecords.systemsreview')),
                ('third_doctor_id', models.ForeignKey(blank=True, limit_choices_to={'thirds__name': 'Medico'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thirds_doctor_id', to='medicalrecords.thirds', verbose_name='Medico')),
                ('third_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicalrecords.thirds')),
            ],
            options={
                'verbose_name': 'records',
                'verbose_name_plural': 'records',
            },
        ),
    ]
