# Generated by Django 5.1 on 2024-08-23 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirds',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medicalrecords.vehicles'),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='type',
            field=models.CharField(blank=True, choices=[('P', 'Paciente / Otros'), ('M', 'Medico'), ('E', 'Entidad'), ('C', 'Clinica')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='values',
            name='type_values',
            field=models.CharField(choices=[('SE', 'SOAT'), ('SM', 'SALARIO MINIMO'), ('FO', 'FOSIGA-ECAT')], default='SE', max_length=2),
        ),
    ]
