# Generated by Django 5.0.6 on 2024-06-28 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='third_doctor_id',
        ),
        migrations.RemoveField(
            model_name='records',
            name='third_id',
        ),
        migrations.AddField(
            model_name='records',
            name='signed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='third_medic',
            field=models.ForeignKey(blank=True, limit_choices_to={'thirds__name': 'Medico'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thirds_medic', to='medicalrecords.thirds', verbose_name='Medico'),
        ),
        migrations.AddField(
            model_name='records',
            name='third_patient',
            field=models.ForeignKey(blank=True, limit_choices_to={'thirds__name': 'Paciente'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thirds_patient', to='medicalrecords.thirds', verbose_name='Paciente'),
        ),
    ]
