# Generated by Django 5.1 on 2024-08-26 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicalrecords', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thirds',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='third_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_entity', to='medicalrecords.thirds', verbose_name='Tercero Entidad'),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='third_medic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_medics', to='medicalrecords.thirds', verbose_name='Tercero Medico'),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='third_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_patients', to='medicalrecords.thirds', verbose_name='Tercero Paciente'),
        ),
        migrations.AddField(
            model_name='records',
            name='third_clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thirds_clinic', to='medicalrecords.thirds', verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='records',
            name='third_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thirds_driver', to='medicalrecords.thirds', verbose_name='Conductor'),
        ),
        migrations.AddField(
            model_name='records',
            name='third_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thirds_entity', to='medicalrecords.thirds', verbose_name='Entidad'),
        ),
        migrations.AddField(
            model_name='records',
            name='third_medic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thirds_medic', to='medicalrecords.thirds', verbose_name='Medico'),
        ),
        migrations.AddField(
            model_name='records',
            name='third_medic_clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thirds_medic_clinic', to='medicalrecords.thirds', verbose_name='Medico'),
        ),
        migrations.AddField(
            model_name='records',
            name='third_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thirds_objects', to='medicalrecords.thirds', verbose_name='Pertenencias'),
        ),
        migrations.AddField(
            model_name='records',
            name='third_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thirds_patient', to='medicalrecords.thirds', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='policy',
            name='third_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thirds_policy_entity', to='medicalrecords.thirds', verbose_name='Entidad'),
        ),
        migrations.AddField(
            model_name='fees',
            name='third_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thirds_entity_fee', to='medicalrecords.thirds', verbose_name='Entidad'),
        ),
        migrations.AddField(
            model_name='availability',
            name='third',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicalrecords.thirds'),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='third_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thirds_driver_vehicle', to='medicalrecords.thirds', verbose_name='Conductor'),
        ),
        migrations.AddField(
            model_name='thirds',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medicalrecords.vehicles'),
        ),
        migrations.AddField(
            model_name='records',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medicalrecords.vehicles'),
        ),
        migrations.AddField(
            model_name='policy',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medicalrecords.vehicles'),
        ),
    ]
