# Generated by Django 5.1 on 2024-08-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='type_values',
            field=models.CharField(choices=[('SE', 'SOAT'), ('SM', 'SALARIO MINIMO'), ('FO', 'FOSIGA-ECAT')], default='SE', max_length=2),
        ),
    ]
