# Generated by Django 5.1 on 2024-08-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0002_alter_values_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='values',
            field=models.CharField(choices=[('SE', 'SOAT'), ('FO', 'FOSIGA-ECAT'), ('SM', 'SALARIO MINIMO')], max_length=2),
        ),
    ]
