# Generated by Django 5.1 on 2024-08-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='values',
            field=models.CharField(choices=[('SE', 'SOAT'), ('SM', 'SALARIO MINIMO'), ('FO', 'FOSIGA-ECAT')], max_length=2),
        ),
    ]
