# Generated by Django 5.1 on 2024-08-30 20:39

import django.db.models.deletion
import medicalrecords.models.records
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalrecords.policy'),
        ),
        migrations.AlterField(
            model_name='values',
            name='type_values',
            field=models.CharField(choices=[('SE', 'SOAT'), ('FO', 'FOSIGA-ECAT'), ('SM', 'SALARIO MINIMO')], max_length=2),
        ),
        migrations.AlterField(
            model_name='values',
            name='year_date',
            field=models.DateField(default=medicalrecords.models.records.defaultGetDate),
        ),
    ]
