# Generated by Django 5.0.6 on 2024-06-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0002_remove_records_third_doctor_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='diagnoses',
            options={'verbose_name': 'Diagnóstico', 'verbose_name_plural': 'Diagnósticos'},
        ),
        migrations.AlterModelOptions(
            name='records',
            options={'verbose_name': 'Registro', 'verbose_name_plural': 'Registros'},
        ),
        migrations.AlterModelOptions(
            name='specialities',
            options={'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='thirds',
            options={'verbose_name': 'Tercero', 'verbose_name_plural': 'Terceros'},
        ),
        migrations.AlterModelTable(
            name='thirds',
            table=None,
        ),
    ]
