# Generated by Django 5.0.6 on 2024-07-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0003_alter_cities_options_alter_diagnoses_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'ordering': ['name'], 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='generalexam',
            options={'verbose_name': 'Examen General', 'verbose_name_plural': 'Examen General'},
        ),
        migrations.AlterModelOptions(
            name='systemsreview',
            options={'verbose_name': 'Revision de Sistemas', 'verbose_name_plural': 'Revision de Sistemas'},
        ),
    ]
