# Generated by Django 5.1 on 2024-09-01 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0003_alter_fees_policy_alter_values_type_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='third_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thirds_entity_vehicle', to='medicalrecords.thirds', verbose_name='Empresa'),
        ),
    ]
