# Generated by Django 5.1 on 2024-08-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0003_alter_values_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirds',
            name='policys',
            field=models.ManyToManyField(blank=True, null=True, to='medicalrecords.policy'),
        ),
        migrations.AlterField(
            model_name='values',
            name='values',
            field=models.CharField(choices=[('FO', 'FOSIGA-ECAT'), ('SM', 'SALARIO MINIMO'), ('SE', 'SOAT')], max_length=2),
        ),
    ]
