# Generated by Django 5.0.6 on 2024-07-02 20:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0004_alter_cities_options_alter_generalexam_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='diagnosis',
            field=models.ForeignKey(blank=True, limit_choices_to={'diagnoses__name': 'Diagnostico'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis', to='medicalrecords.diagnoses', verbose_name='Diagnostico'),
        ),
        migrations.AlterField(
            model_name='records',
            name='diagnosis_1',
            field=models.ForeignKey(blank=True, limit_choices_to={'diagnoses__name': 'Diagnostico'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis_1', to='medicalrecords.diagnoses', verbose_name='Primer Diagnostico'),
        ),
        migrations.CreateModel(
            name='Scheduled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Fecha solicitada')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('confirmed', models.BooleanField()),
                ('speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_specialities', to='medicalrecords.specialities', verbose_name='Especialidad')),
                ('third_medic', models.ForeignKey(blank=True, limit_choices_to={'thirdtypes__name': 'Medico'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_medics', to='medicalrecords.thirds', verbose_name='Tercero Medico')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['date', 'time'],
            },
        ),
    ]
