# Generated by Django 5.1 on 2024-08-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0004_alter_thirds_policys_alter_values_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='values',
            field=models.CharField(choices=[('SM', 'SALARIO MINIMO'), ('SE', 'SOAT'), ('FO', 'FOSIGA-ECAT')], max_length=2),
        ),
    ]
