# Generated by Django 5.1 on 2024-09-05 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0004_vehicles_third_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='number_report_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='obs_value_obj',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='signed_patient',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='third_buddy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thirds_buddy', to='medicalrecords.thirds', verbose_name='Acompañante'),
        ),
    ]
