# Generated by Django 5.1 on 2024-08-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0005_alter_values_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='number_report',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='values',
            name='values',
            field=models.CharField(choices=[('FO', 'FOSIGA-ECAT'), ('SE', 'SOAT'), ('SM', 'SALARIO MINIMO')], max_length=2),
        ),
    ]