# Generated by Django 5.0.6 on 2024-07-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0005_alter_records_diagnosis_alter_records_diagnosis_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnoses',
            options={'ordering': ['name'], 'verbose_name': 'Diagnóstico', 'verbose_name_plural': 'Diagnósticos'},
        ),
        migrations.AlterModelOptions(
            name='generalexam',
            options={'ordering': ['name'], 'verbose_name': 'Examen General', 'verbose_name_plural': 'Examen General'},
        ),
        migrations.AlterModelOptions(
            name='records',
            options={'ordering': ['date_time'], 'verbose_name': 'Registro', 'verbose_name_plural': 'Registros'},
        ),
        migrations.AlterModelOptions(
            name='specialities',
            options={'ordering': ['description'], 'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='systemsreview',
            options={'ordering': ['name'], 'verbose_name': 'Revision de Sistemas', 'verbose_name_plural': 'Revision de Sistemas'},
        ),
        migrations.AlterModelOptions(
            name='thirds',
            options={'ordering': ['nit'], 'verbose_name': 'Tercero', 'verbose_name_plural': 'Terceros'},
        ),
        migrations.AlterField(
            model_name='cities',
            name='departament_dane_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='municipality_dane_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
