# Generated by Django 5.1 on 2024-09-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0005_records_number_report_id_records_obs_value_obj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='descript_procedures',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='diagnosis_multiple',
            field=models.ManyToManyField(blank=True, to='medicalrecords.diagnoses'),
        ),
    ]
