# Generated by Django 5.0.6 on 2024-07-04 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0006_alter_diagnoses_options_alter_generalexam_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirds',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='city_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('N', 'Ninguno'), ('I', 'Indigena'), ('A', 'AfroColombiano'), ('G', 'ROM - Gitano'), ('R', 'Raizal')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='maternity_breasfeeding',
            field=models.CharField(blank=True, choices=[('0', 'Ninguno'), ('1', 'Menos de 1 mes'), ('2', '1 a 3 meses'), ('3', '3 a 6 meses'), ('4', 'Mas de 6 meses'), ('5', 'Mas de 1 año')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='maternity_breasfeeding_complementary',
            field=models.CharField(blank=True, choices=[('0', 'Nunca'), ('1', 'Menos de 1 Mes'), ('2', '1 a 3 meses'), ('3', '3 a 6 meses')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='maternity_breasfeeding_extend',
            field=models.CharField(blank=True, choices=[('0', 'Nunca'), ('1', 'Menos de 1 Mes'), ('2', '1 a 3 meses'), ('3', '3 a 6 meses')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='maternity_pregnancy',
            field=models.CharField(blank=True, choices=[('NI', 'Ninguno'), ('PT', 'Primer Trimestre'), ('ST', 'Segundo Trimestre'), ('TT', 'Tercer Trimestre'), ('PU', 'Puérperio')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='maternity_violence',
            field=models.CharField(blank=True, choices=[('N', 'Ninguno'), ('M', 'Mina ANtipersona'), ('D', 'Desmovilizado'), ('R', 'Reinsertado'), ('I', 'Intrafamiliar')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='sex',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], max_length=1),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medicalrecords.specialities'),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='year_old',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
