# Generated by Django 5.1 on 2024-08-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0007_alter_records_condition_alter_values_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='values',
            name='values',
            field=models.CharField(choices=[('SE', 'SOAT'), ('FO', 'FOSIGA-ECAT'), ('SM', 'SALARIO MINIMO')], max_length=2),
        ),
    ]