# Generated by Django 5.1 on 2024-09-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0007_records_signed_dactilar_alter_values_type_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='values',
            name='val',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
