# Generated by Django 5.0.6 on 2024-07-04 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0007_alter_thirds_address_alter_thirds_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='allergies',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis', to='medicalrecords.diagnoses', verbose_name='Diagnostico'),
        ),
        migrations.AlterField(
            model_name='records',
            name='diagnosis_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis_1', to='medicalrecords.diagnoses', verbose_name='Primer Diagnostico'),
        ),
        migrations.AlterField(
            model_name='records',
            name='diagnosis_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_2', to='medicalrecords.diagnoses', verbose_name='Segundo Diagnostico'),
        ),
        migrations.AlterField(
            model_name='records',
            name='diagnosis_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_3', to='medicalrecords.diagnoses', verbose_name='Tercer Diagnostico'),
        ),
        migrations.AlterField(
            model_name='records',
            name='general_exam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='history',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='reason_consultation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='systems_review',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='third_medic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thirds_medic', to='medicalrecords.thirds', verbose_name='Medico'),
        ),
        migrations.AlterField(
            model_name='records',
            name='third_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thirds_patient', to='medicalrecords.thirds', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='records',
            name='types_general_exam',
            field=models.ManyToManyField(blank=True, null=True, to='medicalrecords.generalexam'),
        ),
        migrations.AlterField(
            model_name='records',
            name='types_systems_review',
            field=models.ManyToManyField(blank=True, null=True, to='medicalrecords.systemsreview'),
        ),
    ]
