# Generated by Django 5.0.6 on 2024-07-04 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0008_alter_records_allergies_alter_records_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled',
            name='third_patient',
            field=models.ForeignKey(blank=True, limit_choices_to={'thirdtypes__name': 'Paciente'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_patients', to='medicalrecords.thirds', verbose_name='Tercero Paciente'),
        ),
    ]
