# Generated by Django 5.1 on 2024-09-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0008_values_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='imghd',
            field=models.ImageField(blank=True, null=True, upload_to='records/'),
        ),
        migrations.AddField(
            model_name='records',
            name='imghdr',
            field=models.ImageField(blank=True, null=True, upload_to='records/'),
        ),
    ]
