# Generated by Django 5.1 on 2024-08-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0009_alter_values_options_remove_values_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='type_values',
            field=models.CharField(choices=[('SM', 'SALARIO MINIMO'), ('SE', 'SOAT'), ('FO', 'FOSIGA-ECAT')], default='SE', max_length=2),
        ),
    ]
