# Generated by Django 5.0.6 on 2024-07-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0009_scheduled_third_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='types_general_exam',
            field=models.ManyToManyField(to='medicalrecords.generalexam'),
        ),
        migrations.AlterField(
            model_name='records',
            name='types_systems_review',
            field=models.ManyToManyField(to='medicalrecords.systemsreview'),
        ),
    ]
