# Generated by Django 5.1.1 on 2024-11-23 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicalrecords", "0010_records_imgls_alter_records_half"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fees",
            name="policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="medicalrecords.policy",
            ),
        ),
        migrations.AlterField(
            model_name="fees",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="medicalrecords.services",
            ),
        ),
        migrations.AlterField(
            model_name="fees",
            name="specialities",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="medicalrecords.specialities",
            ),
        ),
        migrations.AlterField(
            model_name="records",
            name="diagnosis_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="diagnosis_2",
                to="medicalrecords.diagnoses",
                verbose_name="Segundo Diagnostico",
            ),
        ),
        migrations.AlterField(
            model_name="records",
            name="diagnosis_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="diagnosis_3",
                to="medicalrecords.diagnoses",
                verbose_name="Tercer Diagnostico",
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="speciality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="medicalrecords.specialities",
            ),
        ),
    ]
