# Generated by Django 5.0.6 on 2024-07-04 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0010_alter_records_types_general_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled',
            name='third_medic',
            field=models.ForeignKey(blank=True, limit_choices_to={'thirdtypes__name': 'Medico'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_medics', to='medicalrecords.thirds', verbose_name='Tercero Medico'),
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='third_patient',
            field=models.ForeignKey(blank=True, limit_choices_to={'thirdtypes__name': 'Paciente'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_patients', to='medicalrecords.thirds', verbose_name='Tercero Paciente'),
        ),
    ]
