# Generated by Django 5.0.6 on 2024-07-04 21:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0012_remove_scheduled_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled',
            name='speciality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='specialities', to='medicalrecords.specialities', verbose_name='Especialidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='third_medic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_medics', to='medicalrecords.thirds', verbose_name='Tercero Medico'),
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='third_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_patients', to='medicalrecords.thirds', verbose_name='Tercero Paciente'),
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='time',
            field=models.TimeField(default=datetime.time(16, 5, 37, 717201), verbose_name='Hora'),
        ),
    ]
