# Generated by Django 5.1.1 on 2024-12-03 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicalrecords", "0013_thirds_tp"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicamentsRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("dose", models.CharField(blank=True, max_length=100, null=True)),
                ("route", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_records",
                        to="medicalrecords.records",
                        verbose_name="Registro",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="medicalrecords.services",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historia Medica",
                "verbose_name_plural": "Historias Medicas",
                "ordering": ["record", "service__description"],
            },
        ),
    ]
