# Generated by Django 5.0.6 on 2024-07-04 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0014_alter_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled',
            name='time',
            field=models.TimeField(default=datetime.time(16, 6, 21, 876401), verbose_name='Hora'),
        ),
    ]
