# Generated by Django 5.1.1 on 2024-12-03 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicalrecords", "0014_medicamentsrecords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicamentsrecords",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_medical_records",
                to="medicalrecords.services",
                verbose_name="Servicio",
            ),
        ),
    ]
