# Generated by Django 5.1.1 on 2024-12-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "medicalrecords",
            "0016_thirds_profesion_alter_records_descript_procedures_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Accidents",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "external_cause",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GE", "ENF GENERAL"),
                            ("CA", "ACCIDENTE COMUN"),
                            ("TA", "ACCIDENTE TRANSITO"),
                            ("AG", "LESION AGRESION"),
                            ("AU", "LESION AUTOINFLINGIDA"),
                            ("CA", "CATASTROFE"),
                            ("LA", "ACCIDENTE LABORAL"),
                            ("RB", "ACC RBICO U OFIDICO"),
                            ("OT", "OTRO"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "half",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TE", "Telfonico"),
                            ("RA", "Radio"),
                            ("PE", "Personal"),
                            ("OB", "Observado"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AM", "AMBULANCIA"),
                            ("AU", "AUTOMOVIL"),
                            ("MO", "MOTO"),
                            ("CA", "CAMIONETA"),
                            ("BU", "BUS"),
                            ("CA", "CAMION"),
                            ("OT", "OTRO"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Accidente",
                "verbose_name_plural": "Accidentes",
                "ordering": ["date_time"],
            },
        ),
        migrations.AddField(
            model_name="vehicles",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="vehicles",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
