# Generated by Django 5.1.1 on 2024-12-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicalrecords", "0017_accidents_vehicles_latitude_vehicles_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thirds",
            name="occupation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Empleado"),
                    ("I", "Independiente"),
                    ("D", "Desempleado"),
                    ("P", "Pensionado"),
                    ("E", "Estudiante"),
                    ("H", "Hogar"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
