# Generated by Django 5.1.1 on 2025-01-03 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicalrecords", "0018_alter_thirds_occupation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="date_end",
            field=models.DateField(default=datetime.datetime(2025, 12, 31, 0, 0)),
        ),
        migrations.AlterField(
            model_name="policy",
            name="date_start",
            field=models.DateField(default=datetime.datetime(2025, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name="records",
            name="list_injuries",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
