# Generated by Django 5.0.6 on 2024-07-09 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0019_alter_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled',
            name='time',
            field=models.TimeField(default=datetime.time(15, 2, 52, 257986), verbose_name='Hora'),
        ),
    ]
