# Generated by Django 5.0.6 on 2024-07-09 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0020_alter_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='overflow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='time',
            field=models.TimeField(default=datetime.time(15, 14, 39, 919899), verbose_name='Hora'),
        ),
    ]
