# Generated by Django 5.0.6 on 2024-07-09 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0021_availability_overflow_alter_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled',
            name='time',
            field=models.TimeField(default=datetime.time(15, 15, 10, 269883), verbose_name='Hora'),
        ),
    ]
