# Generated by Django 5.0.6 on 2024-07-10 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0023_alter_availability_options_alter_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled',
            name='date',
            field=models.DateField(verbose_name='Fecha solicitada'),
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='third_medic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_medics', to='medicalrecords.thirds', verbose_name='Tercero Medico'),
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='time',
            field=models.TimeField(verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='type',
            field=models.CharField(blank=True, choices=[('P', 'Paciente'), ('M', 'Medico')], max_length=1, null=True),
        ),
    ]
