# Generated by Django 5.0.6 on 2024-07-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0024_alter_scheduled_date_alter_scheduled_third_medic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled',
            name='insurance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='confirmed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
