# Generated by Django 5.0.6 on 2024-07-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0025_scheduled_insurance_alter_scheduled_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled',
            name='date_origin',
            field=models.DateField(default='2021-01-01'),
        ),
    ]
