# Generated by Django 5.0.6 on 2024-07-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0027_alter_scheduled_date_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled',
            name='date_origin',
            field=models.DateField(default='1999-01-01'),
        ),
    ]
