# Generated by Django 5.0.6 on 2024-07-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0028_alter_scheduled_date_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='overflow',
            field=models.IntegerField(default=0),
        ),
    ]
