# Generated by Django 5.0.6 on 2024-07-13 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0029_alter_availability_overflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='medicalrecords.records', verbose_name='Historia'),
        ),
    ]
