# Generated by Django 5.0.6 on 2024-07-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0031_records_details_records_records_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='records_details',
            name='signed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
