# Generated by Django 5.0.6 on 2024-07-16 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0032_records_details_signed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='Records_details',
            new_name='records_details',
        ),
        migrations.RemoveField(
            model_name='records_details',
            name='general_exam',
        ),
        migrations.RemoveField(
            model_name='records_details',
            name='history',
        ),
        migrations.RemoveField(
            model_name='records_details',
            name='systems_review',
        ),
    ]
