# Generated by Django 5.0.6 on 2024-07-17 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0034_remove_records_records_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='records_details',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
