# Generated by Django 5.0.6 on 2024-07-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0035_records_details_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records_details',
            name='signed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
