# Generated by Django 5.0.6 on 2024-07-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0036_alter_records_details_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirds',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('N', 'Ninguno'), ('I', 'Indigena'), ('A', 'AfroColombiano'), ('G', 'ROM - Gitano'), ('R', 'Raizal')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='maternity_breasfeeding',
            field=models.CharField(blank=True, choices=[('NI', 'Ninguno'), ('UM', 'Menos de 1 mes'), ('TM', '1 a 3 meses'), ('SM', '3 a 6 meses'), ('MM', 'Mas de 6 meses'), ('UA', 'Mas de 1 año')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='maternity_breasfeeding_complementary',
            field=models.CharField(blank=True, choices=[('NI', 'Nunca'), ('UM', 'Menos de 1 Mes'), ('TM', '1 a 3 meses'), ('SM', '3 a 6 meses')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='maternity_breasfeeding_extend',
            field=models.CharField(blank=True, choices=[('NI', 'Nunca'), ('UM', 'Menos de 1 Mes'), ('TM', '1 a 3 meses'), ('SM', '3 a 6 meses')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='maternity_violence',
            field=models.CharField(blank=True, choices=[('NI', 'Ninguno'), ('MA', 'Mina ANtipersona'), ('DM', 'Desmovilizado'), ('RS', 'Reinsertado'), ('IN', 'Intrafamiliar')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='type',
            field=models.CharField(blank=True, choices=[('P', 'Paciente'), ('M', 'Medico')], max_length=2, null=True),
        ),
    ]
