# Generated by Django 5.0.6 on 2024-07-22 23:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0037_alter_thirds_ethnicity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Procedimiento',
                'verbose_name_plural': 'Procedimientos',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='records',
            old_name='allergies',
            new_name='live',
        ),
        migrations.AddField(
            model_name='records',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medicalrecords.cities'),
        ),
        migrations.AddField(
            model_name='records',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='ef_fc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='ef_fr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='ef_pa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='ef_temp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='external_cause',
            field=models.CharField(blank=True, choices=[('GE', 'ENF GENERAL'), ('CA', 'ACCIDENTE COMUN'), ('TA', 'ACCIDENTE TRANSITO'), ('AG', 'LESION AGRESION'), ('AU', 'LESION AUTOINFLINGIDA'), ('CA', 'CATASTROFE'), ('LA', 'ACCIDENTE LABORAL'), ('RB', 'ACC RBICO U OFIDICO'), ('OT', 'OTRO')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='glasgow_rm',
            field=models.CharField(blank=True, choices=[('6', 'OBEDECE ORDENES'), ('5', 'LOCALIZA DOLOR'), ('4', 'FLEXION NORMAL'), ('3', 'FLEXION ANORMAL'), ('2', 'EXTENSION'), ('1', 'NINGUNA')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='glasgow_ro',
            field=models.CharField(blank=True, choices=[('4', 'ESPOTANEA'), ('3', 'A ESTIMULO VERBAL'), ('2', 'A ESTIMULO DOLOROSO'), ('1', 'NINGUNA')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='glasgow_rv',
            field=models.CharField(blank=True, choices=[('5', 'ORIENTADO'), ('4', 'CONFUSO'), ('3', 'PALABRAS INADECUADAS'), ('2', 'SONIDOS INADECUADOS'), ('1', 'NINGUNA')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='half',
            field=models.CharField(blank=True, choices=[('TE', 'Telfonico'), ('RA', 'Padio'), ('PE', 'Personal'), ('OB', 'Observado')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='obj',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='observations',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='priority',
            field=models.CharField(blank=True, choices=[('W', 'White'), ('R', 'Red'), ('Y', 'Yellow'), ('G', 'Green'), ('B', 'Black')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='relationship',
            field=models.CharField(blank=True, choices=[('PA', 'PADRE'), ('MA', 'MADRE'), ('HO', 'HIJO'), ('HE', 'HERMAN@'), ('SO', 'SOBRIN@'), ('CO', 'CONYUGE'), ('PR', 'PRIM@'), ('AB', 'ABUEL@'), ('NI', 'NIET@'), ('TI', 'TI@'), ('SU', 'SUEGR@'), ('CU', 'CUÑAD@'), ('OT', 'OTRO')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='relationship_obj',
            field=models.CharField(blank=True, choices=[('PA', 'PADRE'), ('MA', 'MADRE'), ('HO', 'HIJO'), ('HE', 'HERMAN@'), ('SO', 'SOBRIN@'), ('CO', 'CONYUGE'), ('PR', 'PRIM@'), ('AB', 'ABUEL@'), ('NI', 'NIET@'), ('TI', 'TI@'), ('SU', 'SUEGR@'), ('CU', 'CUÑAD@'), ('OT', 'OTRO')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='signed_driver',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='signed_recived',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='third_clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thirds_clinic', to='medicalrecords.thirds', verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='records',
            name='third_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thirds_entity', to='medicalrecords.thirds', verbose_name='Entidad'),
        ),
        migrations.AddField(
            model_name='records',
            name='third_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thirds_objects', to='medicalrecords.thirds', verbose_name='Pertenencias'),
        ),
        migrations.AddField(
            model_name='records',
            name='third_relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thirds_relationship', to='medicalrecords.thirds', verbose_name='Acompañante'),
        ),
        migrations.AddField(
            model_name='records',
            name='time_end',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='records',
            name='time_start',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='records',
            name='value_obj',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='zone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='thirds',
            name='allergies',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thirds',
            name='liquids_foods',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thirds',
            name='medications',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thirds',
            name='occupation',
            field=models.CharField(blank=True, choices=[('E', 'Empleado'), ('I', 'Independiente'), ('D', 'Desempleado'), ('P', 'Pensionado'), ('E', 'Estudiante'), ('H', 'Hogar')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='thirds',
            name='pathologies',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thirds',
            name='status',
            field=models.CharField(blank=True, choices=[('S', 'Soltero'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viudo'), ('U', 'Union Libre')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medicalrecords.cities'),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='city_birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='city_birth', to='medicalrecords.cities'),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='zone',
            field=models.CharField(blank=True, choices=[('U', 'Urbana'), ('R', 'Rural')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('plate', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('AU', 'AUTOMOVIL'), ('MO', 'MOTO'), ('CA', 'CAMIONETA'), ('BU', 'BUS'), ('CA', 'CAMION'), ('OT', 'OTRO')], max_length=2)),
                ('third_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thirds_policy_entity', to='medicalrecords.thirds', verbose_name='Entidad')),
            ],
            options={
                'verbose_name': 'Poliza',
                'verbose_name_plural': 'Polizas',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='records',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policy', to='medicalrecords.policy', verbose_name='Poliza'),
        ),
        migrations.AddField(
            model_name='records',
            name='procedures',
            field=models.ManyToManyField(to='medicalrecords.procedures'),
        ),
    ]
