# Generated by Django 5.0.6 on 2024-07-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0039_records_procedures_others_alter_records_procedures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='observations',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
