# Generated by Django 5.0.6 on 2024-07-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0041_records_signed_obj_records_signed_profesional_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
