# Generated by Django 5.0.6 on 2024-07-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0042_alter_records_time_end_alter_records_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
