# Generated by Django 5.0.6 on 2024-07-26 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0044_remove_records_signed_profesional_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='third_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thirds_driver', to='medicalrecords.thirds', verbose_name='Conductor'),
        ),
    ]
