# Generated by Django 5.0.6 on 2024-07-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0045_records_third_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='body',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
