# Generated by Django 5.0.6 on 2024-07-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0046_records_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='body_side',
            field=models.CharField(blank=True, choices=[('GL', 'Glutea'), ('AM', 'Anterior Muslo'), ('PM', 'Posterior Muslo'), ('AR', 'Anterior Rodilla'), ('PR', 'Posterior Rodilla'), ('AP', 'Anterior Pierna'), ('PP', 'Posterior Pierna'), ('TA', 'Tobillo anterior'), ('TP', 'Tobullo posterior'), ('PI', 'Pie')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='body',
            field=models.CharField(blank=True, choices=[('CA', 'Cabeza'), ('CU', 'Cuello'), ('TO', 'Torax'), ('DO', 'Dorso'), ('AB', 'Abdomen'), ('PE', 'Pelvis/Perine'), ('MI', 'Miembro Inferior'), ('SU', 'Miembro Superior')], max_length=2, null=True),
        ),
    ]
