# Generated by Django 5.0.6 on 2024-07-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0047_records_body_side_alter_records_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='injuries',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
