# Generated by Django 5.0.6 on 2024-07-26 16:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0048_records_injuries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='body',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CA', 'Cabeza'), ('CU', 'Cuello'), ('TO', 'Torax'), ('DO', 'Dorso'), ('AB', 'Abdomen'), ('PE', 'Pelvis/Perine'), ('MI', 'Miembro Inferior'), ('SU', 'Miembro Superior')], max_length=300), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='records',
            name='body_side',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('GL', 'Glutea'), ('AM', 'Anterior Muslo'), ('PM', 'Posterior Muslo'), ('AR', 'Anterior Rodilla'), ('PR', 'Posterior Rodilla'), ('AP', 'Anterior Pierna'), ('PP', 'Posterior Pierna'), ('TA', 'Tobillo anterior'), ('TP', 'Tobullo posterior'), ('PI', 'Pie')], max_length=300), blank=True, null=True, size=None),
        ),
    ]
