# Generated by Django 5.0.6 on 2024-07-26 16:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0049_alter_records_body_alter_records_body_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='body',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='records',
            name='body_side',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, null=True, size=None),
        ),
    ]
