# Generated by Django 5.0.6 on 2024-07-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0050_alter_records_body_alter_records_body_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirds',
            name='type_document',
            field=models.CharField(blank=True, choices=[('CC', 'Cedula de Ciudadania'), ('CE', 'Cedula de Extranjeria'), ('PA', 'Pasaporte'), ('RC', 'Registro Civil'), ('TI', 'Tarjeta de Identidad'), ('NU', 'Numero Unico de Identificacion'), ('PE', 'Permiso Especial de Permanencia'), ('AS', 'Adulto sin Identificacion'), ('NI', 'Nit')], default='CC', max_length=2, null=True),
        ),
    ]
