# Generated by Django 5.0.6 on 2024-07-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0051_thirds_type_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='imgcc',
            field=models.ImageField(blank=True, null=True, upload_to='records/'),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='second_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thirds',
            name='second_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
