# Generated by Django 5.0.6 on 2024-08-01 03:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0052_records_imgcc_alter_thirds_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='plate',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='policy',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2024, 12, 31, 0, 0)),
        ),
        migrations.AddField(
            model_name='policy',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2024, 1, 1, 0, 0)),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=300)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalrecords.specialities')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Specialities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalrecords.specialities')),
                ('third_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thirds_entity_fee', to='medicalrecords.thirds', verbose_name='Entidad')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalrecords.services')),
            ],
            options={
                'verbose_name': 'Honorario',
                'verbose_name_plural': 'Honorarios',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('plate', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('AU', 'AUTOMOVIL'), ('MO', 'MOTO'), ('CA', 'CAMIONETA'), ('BU', 'BUS'), ('CA', 'CAMION'), ('OT', 'OTRO')], max_length=2)),
                ('third_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thirds_driver_vehicle', to='medicalrecords.thirds', verbose_name='Conductor')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'ordering': ['brand'],
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medicalrecords.vehicles'),
        ),
    ]
