# Generated by Django 5.0.6 on 2024-08-01 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0053_remove_policy_brand_remove_policy_plate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medicalrecords.policy'),
        ),
        migrations.AddField(
            model_name='policy',
            name='amount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='policy',
            name='name',
            field=models.CharField(default='Contrato', max_length=100),
        ),
        migrations.AddField(
            model_name='policy',
            name='payment_model',
            field=models.CharField(choices=[('FF', 'FONDO FIJO'), ('EV', 'EVENTO'), ('SE', 'SEGURO SOAT')], default='SE', max_length=2),
        ),
    ]
