# Generated by Django 5.0.6 on 2024-08-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0054_fees_policy_policy_amount_total_policy_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='number',
            field=models.CharField(max_length=30),
        ),
    ]
