# Generated by Django 5.0.6 on 2024-08-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0055_alter_policy_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['description'], 'verbose_name': 'Poliza', 'verbose_name_plural': 'Polizas'},
        ),
        migrations.RenameField(
            model_name='fees',
            old_name='Specialities',
            new_name='specialities',
        ),
        migrations.RenameField(
            model_name='policy',
            old_name='number',
            new_name='description',
        ),
        migrations.AddField(
            model_name='policy',
            name='type_police',
            field=models.CharField(choices=[('MP', 'MEDICINA PREPAGADA'), ('PS', 'SUBSIDIADA'), ('PC', 'CONTRIBUTIVO'), ('SE', 'SOAT')], default='SE', max_length=2),
        ),
    ]
