# Generated by Django 5.0.6 on 2024-08-01 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0056_alter_policy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medicalrecords.fees'),
        ),
        migrations.AddField(
            model_name='records',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medicalrecords.services'),
        ),
        migrations.AlterField(
            model_name='records',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medicalrecords.policy'),
        ),
    ]
