# Generated by Django 5.0.6 on 2024-08-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0057_records_fee_records_service_alter_records_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='imgco',
            field=models.ImageField(blank=True, null=True, upload_to='records/'),
        ),
        migrations.AddField(
            model_name='records',
            name='imgic',
            field=models.ImageField(blank=True, null=True, upload_to='records/'),
        ),
        migrations.AddField(
            model_name='records',
            name='imglc',
            field=models.ImageField(blank=True, null=True, upload_to='records/'),
        ),
        migrations.AddField(
            model_name='records',
            name='imgso',
            field=models.ImageField(blank=True, null=True, upload_to='records/'),
        ),
        migrations.AddField(
            model_name='records',
            name='imgtp',
            field=models.ImageField(blank=True, null=True, upload_to='records/'),
        ),
    ]
