# Generated by Django 5.0.6 on 2024-08-02 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0058_records_imgco_records_imgic_records_imglc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled',
            name='fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='medicalrecords.fees', verbose_name='Tarifa'),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sheduled_policy', to='medicalrecords.policy', verbose_name='Poliza'),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='medicalrecords.services', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='scheduled',
            name='third_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_entity', to='medicalrecords.thirds', verbose_name='Tercero Entidad'),
        ),
    ]
