# Generated by Django 5.0.6 on 2024-08-05 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0060_alter_fees_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.CharField(choices=[('SO', 'SOAT'), ('SM', 'SALARIO MINIMO'), ('FO', 'FOSIGA-ECAT')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('year_date', models.DateField(default=datetime.datetime(2024, 1, 1, 0, 0))),
            ],
        ),
        migrations.AddField(
            model_name='services',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
