# Generated by Django 5.0.6 on 2024-08-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0062_thirds_policys_alter_records_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='template',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='policy',
            name='type_police',
            field=models.CharField(choices=[('SE', 'SOAT'), ('AD', 'ADRES'), ('EP', 'EAPB'), ('PA', 'PARTICULAR'), ('EZ', 'ZONA SEGURA'), ('AR', 'ARL'), ('MP', 'MEDICINA PREPAGADA'), ('VI', 'VINCULADOS')], default='SE', max_length=2),
        ),
        migrations.AlterField(
            model_name='values',
            name='values',
            field=models.CharField(choices=[('FO', 'FOSIGA-ECAT'), ('SM', 'SALARIO MINIMO'), ('SO', 'SOAT')], max_length=2),
        ),
    ]
