# Generated by Django 5.0.6 on 2024-08-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0064_remove_fees_code_policy_template_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='values',
            field=models.CharField(choices=[('SE', 'SOAT'), ('SM', 'SALARIO MINIMO'), ('FO', 'FOSIGA-ECAT')], max_length=2),
        ),
    ]
