# Generated by Django 5.0.6 on 2024-08-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0066_rename_amount_services_amount_particular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='values',
            field=models.CharField(choices=[('SM', 'SALARIO MINIMO'), ('SE', 'SOAT'), ('FO', 'FOSIGA-ECAT')], max_length=2),
        ),
    ]
