# Generated by Django 5.0.6 on 2024-08-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0067_alter_values_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirds',
            name='policys',
            field=models.ManyToManyField(blank=True, null=True, to='medicalrecords.policy'),
        ),
        migrations.AlterField(
            model_name='values',
            name='values',
            field=models.CharField(choices=[('SM', 'SALARIO MINIMO'), ('FO', 'FOSIGA-ECAT'), ('SE', 'SOAT')], max_length=2),
        ),
    ]
