# Generated by Django 5.0.6 on 2024-08-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0069_records_list_injuries_alter_values_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='list_injuries',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
