# Generated by Django 5.0.6 on 2024-08-09 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0070_alter_records_list_injuries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='values',
            options={'ordering': ['values'], 'verbose_name': 'Valor', 'verbose_name_plural': 'Valores'},
        ),
        migrations.AlterField(
            model_name='thirds',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='values',
            name='values',
            field=models.CharField(choices=[('FO', 'FOSIGA-ECAT'), ('SE', 'SOAT'), ('SM', 'SALARIO MINIMO')], max_length=2),
        ),
    ]
